<a href="https://colab.research.google.com/github/kny8/data_analysis/blob/main/Python_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy:
## Basics


In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Two dimensional arrays


In [5]:
b = np.array([[9,8,6],[10,5,4]])
print(b)

[[ 9  8  6]
 [10  5  4]]


1. Get dimension of numpy arrays;


In [8]:
# dimension of array a
a.ndim

2

2. Shape (rows, columns)

In [10]:
# shape (rows, columns)
a.shape


(2, 3)

In [11]:
b.shape

(2, 3)

3. Type of array:

In [12]:
a.dtype

dtype('int64')

4. Size of array:


In [13]:
a.itemsize

8

5. Initializing data type with array



---
By default the the array is of size int 64. each bytes has 8 bits. So, size = no. of byte = 64/8 = 8


In [14]:
c = np.array([1,2,3], dtype='int16')

In [16]:
print (f' Size of c is {c.itemsize} and type of c is {c.dtype}')

 Size of c is 2 and type of c is int16


6. Total size

In [17]:
a.nbytes

24

## Accessing/ Changing specific elements, rows, cloumns, etc
