<a href="https://colab.research.google.com/github/kny8/data_analysis/blob/main/Python_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy:
## Basics


In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Two dimensional arrays


In [ ]:
b = np.array([[9,8,6],[10,5,4]])
print(b)

[[ 9  8  6]
 [10  5  4]]


1. Get dimension of numpy arrays;


In [ ]:
# dimension of array a
a.ndim

2

2. Shape (rows, columns)

In [ ]:
# shape (rows, columns)
a.shape


(2, 3)

In [ ]:
b.shape

(2, 3)

3. Type of array:

In [ ]:
a.dtype

dtype('int64')

4. Size of array:


In [ ]:
a.itemsize

8

5. Initializing data type with array



---
By default the the array is of size int 64. each bytes has 8 bits. So, size = no. of byte = 64/8 = 8


In [ ]:
c = np.array([1,2,3], dtype='int16')

In [ ]:
print (f' Size of c is {c.itemsize} and type of c is {c.dtype}')

 Size of c is 2 and type of c is int16


6. Total size

In [ ]:
a.nbytes

24

## Accessing/ Changing specific elements, rows, cloumns, etc


In [23]:
c = np.array ([[1,2,3,4,5,6,7,8],[5,6,7,8,9,0,10,11]])

Accessing element

In [6]:
# access element using [index_row, index_columnn]
c[1,5]
# direclty using index gives the type as well as the value
# we can use print statement just to get the values
# indexing starts with 0

np.int64(0)

In [7]:
print(c[1,5])

0


Getting an entire row

In [9]:
# Get all the value in a given row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7, 8])

Getting an entire column

In [11]:
# Getting the value of an entire column
c[:,0]

array([1, 5])

Getting values of certian element of a column or a row

In [15]:
# using [ start_index:end_index:stepsize]

c [0 , 1:6:2]
# From first row take value from second element(1) to fifth index as last index is exlucdec and skip by 2)

array([2, 4, 6])

Replacing the value in an array:

In [25]:
# Specify the exact index you want replace [r,c]
c[1,5]= 2
print(c)

[[ 1  2 17  4  5  6  7  8]
 [ 5  6 17  8  9  2 10 11]]


Changing an entire row or a column

In [26]:
# Replace an entire column by a single value
c[: ,2]= 17
print(c)

[[ 1  2 17  4  5  6  7  8]
 [ 5  6 17  8  9  2 10 11]]


In [30]:
# We can also specify indivisual value
# The number of value should be equal to number of rows or column we are chaning
c [:, 3]=[19,21]
print(c)

[[ 1  2 17 19  5  6  7  8]
 [ 5  6 17 21  9  2 10 11]]


## Mathematics using numpy


In [4]:
math= np.array([1,2,3,4])
print (math)

[1 2 3 4]


In [10]:
# Addition in numpy


# Method 1:
print(math + 2)

# Method 2:
print(np.add(math,2))

[3 4 5 6]
[3 4 5 6]


In [12]:
# Subtraction in numpy

# Method 1
print(math - 2)

# Method 2
print(np.subtract(math,2))

[-1  0  1  2]
[-1  0  1  2]


In [15]:
# Multiplication in numpy

# Method 1
print(math*2)

#Method 2
print(np.multiply(math,2))

[2 4 6 8]
[2 4 6 8]
